#ifndef __AboutDialog__
#define __AboutDialog__

/**
@file
Subclass of AboutDialogBase, which is generated by wxFormBuilder.
*/

#include "Forms.h"

//// end generated include

/** Implementing AboutDialogBase */
class AboutDialog : public AboutDialogBase
        {
        protected:
            // Handlers for AboutDialogBase events.
            /// TODO
            void OnWebsiteHyperlinkClick( wxHyperlinkEvent& event ) { };
        public:
            /** Constructor */
            AboutDialog( wxWindow* parent );
            //// end generated class members


        };

#endif // __AboutDialog__
