#ifndef __MainFrame__
#define __MainFrame__

/**
@file
Subclass of MainFrameBase, which is generated by wxFormBuilder.
*/

#include "Forms.h"

//// end generated include

/** Implementing MainFrameBase */
class MainFrame : public MainFrameBase {
protected:
    // Handlers for MainFrameBase events.
    void OnPreferencesMenuItemSelected(wxCommandEvent &event);

    void OnTextInput(wxCommandEvent &event);

    void OnEncryptButtonClick(wxCommandEvent &event);

    void OnClose(wxCloseEvent &event);

    void LoadPreferences();

    void SavePreferences() const;

public:
    /** Constructor */
    MainFrame(wxWindow *parent);
    //// end generated class members
};

#endif // __MainFrame__
