#ifndef ENIGMAWXWIDGETS_PREFERENCESDIALOG_HPP
#define ENIGMAWXWIDGETS_PREFERENCESDIALOG_HPP

#include <wx/msgdlg.h>
/**
@file
Subclass of PreferencesDialogBase, which is generated by wxFormBuilder.
*/

#include "Forms.h"

//// end generated include


#include "../UserPreferences.hpp"

/** Implementing PreferencesDialogBase */
class PreferencesDialog : public PreferencesDialogBase {

protected:
    // Handlers for PreferencesDialogBase events.
    void OnOkButtonClick(wxCommandEvent &event);

    void OnCancelButtonClick(wxCommandEvent &event) { Close(); }

    UserPreferences Preferences;
public:
    /** Constructor */
    PreferencesDialog(wxWindow *parent);
    //// end generated class members

};

#endif //ENIGMAWXWIDGETS_PREFERENCESDIALOG_HPP
